#!/usr/bin/env python3
"""
Regenerate the compact Northern New York map used in the homepage hero.

The hero map is a crop of the statewide county map, not new geometry. This
script reads the county paths that tools/build_map.py already generated
(_includes/nc-counties.svg.html), keeps the eight Northern New York counties,
and works out a viewBox tight around them. Because the paths are reused as-is,
the crop stays in the same coordinate system as _data/map_meta.yml, so the pin
x/y values in _data/map_pins.yml keep working without any conversion.

It also builds the corner inset: a single outline of New York State with the
eight-county region as a second outline on top, both dissolved from the
county paths and simplified hard, because the inset renders about 90px wide.

    pip install shapely        # build-time only; the site needs nothing
    python3 tools/build_nny_map.py

Outputs: _includes/nny-counties.svg.html   (8 county paths for the main map)
         _includes/nny-inset.svg.html      (state + region outlines)
         _data/nny_map_meta.yml            (viewBoxes for both)
"""

import os
import re

from shapely.geometry import Polygon
from shapely.ops import unary_union

# The region, as defined in our positioning copy. Keep in step with the
# footer, the map <desc>, and the homepage hero.
NNY = [
    "Oneida", "Oswego", "Herkimer", "Lewis",
    "Jefferson", "St. Lawrence", "Hamilton", "Franklin",
]

# Breathing room around the eight counties, in source user units. Enough that
# a pin halo on the edge (Watertown sits close to Lake Ontario) is not clipped.
PAD = 10.0

# Inset simplification tolerance, in source user units (the state is 960 wide).
INSET_TOLERANCE = 4.0

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_includes", "nc-counties.svg.html")

PATH_RE = re.compile(r'<path class="[^"]*" d="([^"]+)"><title>(.+?) County</title></path>')


def parse_rings(d):
    """Split an M...L...Z path (as written by build_map.py) into point rings."""
    rings = []
    for chunk in d.split("M")[1:]:
        chunk = chunk.rstrip("Z")
        pts = []
        for pair in chunk.split("L"):
            x, y = pair.split()
            pts.append((float(x), float(y)))
        rings.append(pts)
    return rings


def to_d(geom):
    """Shapely (Multi)Polygon exterior rings -> compact SVG path data."""
    polys = [geom] if geom.geom_type == "Polygon" else list(geom.geoms)
    parts = []
    for poly in polys:
        coords = list(poly.exterior.coords)[:-1]
        if len(coords) < 3:
            continue
        parts.append("M" + "L".join("%.0f %.0f" % c for c in coords) + "Z")
    return "".join(parts)


def main():
    with open(SRC) as fh:
        src = fh.read()

    counties = {}
    for d, name in PATH_RE.findall(src):
        counties[name] = d
    missing = [n for n in NNY if n not in counties]
    if missing:
        raise SystemExit("counties not found in %s: %s" % (SRC, missing))

    # ---- Main map: the eight paths, verbatim, with a tight viewBox ----
    xs, ys = [], []
    for name in NNY:
        for ring in parse_rings(counties[name]):
            xs += [p[0] for p in ring]
            ys += [p[1] for p in ring]
    minx, miny = min(xs) - PAD, min(ys) - PAD
    w, h = max(xs) - min(xs) + 2 * PAD, max(ys) - min(ys) + 2 * PAD

    lines = [
        '<!-- Generated by tools/build_nny_map.py - do not hand-edit.',
        '     The eight Northern New York counties, cropped from',
        '     _includes/nc-counties.svg.html. Same coordinate system, so',
        '     pins from _data/map_pins.yml drop in unchanged. County names',
        '     ride on data-label for the hover/tap label, not <title>, so a',
        '     native tooltip does not double up with it. -->',
    ]
    for name in NNY:
        lines.append(
            '<path class="nny-county" data-label="%s County" d="%s"></path>'
            % (name, counties[name])
        )
    out = os.path.join(ROOT, "_includes", "nny-counties.svg.html")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s (%.1f KB)" % (out, os.path.getsize(out) / 1024.0))

    # ---- Inset: dissolved outlines of the state and the region ----
    def dissolve(names):
        polys = []
        for n in names:
            for ring in parse_rings(counties[n]):
                if len(ring) >= 3:
                    polys.append(Polygon(ring).buffer(0))
        # A small buffer out and back closes the hairline slivers between
        # neighbouring counties that simplification leaves behind.
        merged = unary_union(polys).buffer(1.5).buffer(-1.5)
        merged = merged.simplify(INSET_TOLERANCE, preserve_topology=True)
        # Drop islands too small to see at inset size.
        if merged.geom_type == "MultiPolygon":
            keep = [p for p in merged.geoms if p.area > 150]
            merged = unary_union(keep)
        return merged

    state = dissolve(counties.keys())
    region = dissolve(NNY)
    sminx, sminy, smaxx, smaxy = state.bounds

    inset = [
        '<!-- Generated by tools/build_nny_map.py - do not hand-edit.',
        '     Corner inset: New York State outline, Northern New York filled. -->',
        '<path class="nny-inset-state" d="%s"></path>' % to_d(state),
        '<path class="nny-inset-region" d="%s"></path>' % to_d(region),
    ]
    out = os.path.join(ROOT, "_includes", "nny-inset.svg.html")
    with open(out, "w") as fh:
        fh.write("\n".join(inset) + "\n")
    print("wrote %s (%.1f KB)" % (out, os.path.getsize(out) / 1024.0))

    meta = os.path.join(ROOT, "_data", "nny_map_meta.yml")
    with open(meta, "w") as fh:
        fh.write("# Generated by tools/build_nny_map.py. viewBoxes for the hero map.\n")
        fh.write("# The main map shares its coordinate system with _data/map_meta.yml.\n")
        fh.write('viewbox: "%.1f %.1f %.1f %.1f"\n' % (minx, miny, w, h))
        fh.write("width: %.1f\n" % w)
        fh.write("height: %.1f\n" % h)
        fh.write('inset_viewbox: "%.0f %.0f %.0f %.0f"\n'
                 % (sminx - 4, sminy - 4, smaxx - sminx + 8, smaxy - sminy + 8))
    print("wrote %s" % meta)


if __name__ == "__main__":
    main()
